version: '2'
services:
  euro-tickets-postgresql:
    image: postgres:12.3
    volumes:
      - ~/volumes/jhipster/euro-tickets/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=euro_tickets_user
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
